apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - {{ .Values.deployment.nodegroup }}
      containers:
      - name: {{ .Values.deployment.containers.name }}
        image: {{ .Values.deployment.containers.image }}:{{ .Values.deployment.containers.version }}
        ports:
        - containerPort: {{ .Values.deployment.containers.port }}
        resources:
          limits:
            cpu: {{ .Values.deployment.containers.cpu }}
            memory: {{ .Values.deployment.containers.memory }}